tunnel: 44264acb-afd5-4dae-b928-3550da56e837
credentials-file: /etc/cloudflared/creds.json

ingress:
  # Frontend - main app
  - hostname: my-life-abroad.com
    service: http://frontend:3000
  
  # Frontend - www subdomain
  - hostname: www.my-life-abroad.com
    service: http://frontend:3000
  
  # Backend API
  - hostname: api.my-life-abroad.com
    service: http://server:8000
  
  # MinIO file storage (optional - for direct file access)
  - hostname: files.my-life-abroad.com
    service: http://minio:9000
  
  # Catch-all rule (required)
  - service: http_status:404