name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  server-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install -r apps/server/requirements-dev.txt

      - name: Run tests
        run: |
          PYTHONPATH=apps/server pytest -q apps/server/tests